### ISSUE TITLE
API with couchdb

### ISSUE THREAD

**Issue by chgarnier** [Altoros/fabric-rest#4]
I am using Altoros - Fabric Rest to have API to Fabric network. We i use levelDB it work well but when i use couchDB it doesn't work. I have the following error :+1: 

[2018-10-04 14:20:59.524] [ERROR] peer-listener - (((((((((((( Got block error )))))))))))
[2018-10-04 14:20:59.524] [ERROR] peer-listener - { Error: 14 UNAVAILABLE: Connect Failed
    at createStatusError (/usr/src/app/node_modules/grpc/src/client.js:64:15)
    at ClientDuplexStream._emitStatusIfDone (/usr/src/app/node_modules/grpc/src/client.js:270:19)
    at ClientDuplexStream._readsDone (/usr/src/app/node_modules/grpc/src/client.js:236:8)
    at readCallback (/usr/src/app/node_modules/grpc/src/client.js:296:12)
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Connect Failed' }

If you have any idea of what happen, please let me know

**Comment by push1st1k** [comment]
Hi @chgarnier, which version of Fabric are you using?

**Comment by chgarnier** [comment]
I am using V1.2.

**Comment by push1st1k** [comment]
@chgarnier according the error message, the problem is with connecting to the peer. First of all, I'd recommend to check peer and couchdb logs. After that please try to perform any operation (invoke the chaincode, list channels etc) using cli.

**Comment by chgarnier** [comment]
Yes I did. 

In fact I add this lines in network-config.json : 


`				"couchdb-ip-addr" : "http://couchdb.ORG.DOMAIN",
				"couchdb-port" : "5984",
				"key-value-store" : "fabric-client/lib/impl/CouchDBKeyValueStore.js"
`

It works fine now !

Thanks

**Comment by push1st1k** [comment]
good to hear that!
